<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW6t8elb\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW6t8elb/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerW6t8elb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerW6t8elb\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerW6t8elb\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'W6t8elb',
    'container.build_id' => '9083b100',
    'container.build_time' => 1586172551,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW6t8elb');
