<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP45ztio\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP45ztio/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerP45ztio.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerP45ztio\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerP45ztio\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'P45ztio',
    'container.build_id' => '34631c28',
    'container.build_time' => 1586161496,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP45ztio');
