<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerULcjl4h\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerULcjl4h/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerULcjl4h.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerULcjl4h\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerULcjl4h\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'ULcjl4h',
    'container.build_id' => '2ccdb8a9',
    'container.build_time' => 1586178977,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerULcjl4h');
