<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEu7aDTx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEu7aDTx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEu7aDTx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEu7aDTx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEu7aDTx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Eu7aDTx',
    'container.build_id' => 'd0bddd0b',
    'container.build_time' => 1585732276,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEu7aDTx');
