<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYbhXisZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYbhXisZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYbhXisZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYbhXisZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYbhXisZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YbhXisZ',
    'container.build_id' => '65aaffc7',
    'container.build_time' => 1586161488,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYbhXisZ');
